# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BrainFights' do

pod 'RestKit', '~> 0.24.0'
pod 'JVFloatingDrawer'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'LMDropdownView'

end

